# Generated by Django 5.2.8 on 2025-11-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus_arrival_past',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeid', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('remainseatcnt1', models.IntegerField()),
                ('vehid1', models.IntegerField()),
                ('station_num', models.IntegerField()),
            ],
            options={
                'db_table': 'bus_arrival_train_data',
            },
        ),
    ]
